Update dotnet-build.yml

diff --git a/.github/workflows/dotnet-build.yml b/.github/workflows/dotnet-build.yml
--- a/.github/workflows/dotnet-build.yml
+++ b/.github/workflows/dotnet-build.yml
@@ -8,10 +8,53 @@ on:
 
 jobs:
   print-runtime-context:
-    runs-on:  ubuntu-latest
+    runs-on: ubuntu-latest
 
     steps:
       - name: 🔔 Start build process...
         run: echo "Build process has started"
-    
-  
+        
+
+      - &echo-template
+        name: Echo template
+        run: echo "This is a reusable step."
+        shell: bash
+
+      - name: 📄 Show runtime context
+        run: |
+          echo "🔧 Runner OS: ${{ runner.os }}"
+          echo "📦 Repository: ${{ github.repository }}"
+          echo "👷 Workflow: ${{ github.workflow }}"
+          echo "🚀 Triggered by: ${{ github.event_name }}"
+          echo "🥷 Actor: ${{ github.actor }}"
+          echo "🔢 Run number: ${{ github.run_number }}"
+          echo "🌳 Branch: ${{ github.ref }}"
+
+      - *echo-template
+
+  build-project:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v5.0.0
+
+      - name: Install .NET 9
+        uses: actions/setup-dotnet@v5.0.0
+        with: 
+          dotnet-version: '9-0-x'
+
+      - name: Build project
+        run: | 
+          dotnet build
+          exit 1
+      
+      - name: Run code
+        if: success()
+        run: dotnet run --project CleanCodeDevOps.App/CleanCodeDevOps.App.csproj
+        
+      - name: Failed to build 
+        if: failure()
+        run: echo "Failed to build project" 
+
+      
